application: health-expert-1705
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: api3.app
  secure: always

- url: /s
  static_dir: s
  secure: always

- url: /c1
  static_dir: c1
  secure: always

- url: /c2
  static_dir: c2
  secure: always

- url: /c
  static_dir: c
  secure: always  

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: ssl
  version: latest
- name: jinja2
  version: latest           
  