/*
 * JS for profile generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '571c8f48-30e4-4f79-bcd1-002410b6b1dd';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "selectScreen",
    "location": "selectScreen.html"
}];

profile_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_33': 'profile_mobilegrid_33',
        'mobilegridcell_34': 'profile_mobilegridcell_34',
        'mobileimage_45': 'profile_mobileimage_45',
        'mobilegridcell_35': 'profile_mobilegridcell_35',
        'mobilelabel_31': 'profile_mobilelabel_31',
        'mobilegridcell_38': 'profile_mobilegridcell_38',
        'mobileimage_40': 'profile_mobileimage_40',
        'mobilegridcell_41': 'profile_mobilegridcell_41',
        'mobileimage_42': 'profile_mobileimage_42',
        'mobilegrid_11': 'profile_mobilegrid_11',
        'mobilegridcell_12': 'profile_mobilegridcell_12',
        'mobilelabel_16': 'profile_mobilelabel_16',
        'mobilegrid_23': 'profile_mobilegrid_23',
        'mobilegridcell_24': 'profile_mobilegridcell_24',
        'mobiletextinput_46': 'profile_mobiletextinput_46',
        'mobilegridcell_25': 'profile_mobilegridcell_25',
        'mobilebutton_29': 'profile_mobilebutton_29'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 536px;user-zoom: fixed;max-zoom: 1;min-zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;max-zoom:1;min-zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'profile';

    /*
     * Nonvisual components
     */
    var datasources = [];

    messageDataSource = new Apperyio.DataSource(messages, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("profile");
        },
        'onSuccess': function(data) {
            var t = localStorage.getItem("timer");

            clearInterval(t);

            t = setInterval(function() {
                messageDataSource.execute({
                    'channel': localStorage.getItem('channel'),
                    'ts': localStorage.getItem('ts')
                });
            }, 5000);

            localStorage.setItem("timer", t);

            console.log("t1");;
        },
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['items'],
            'ID': 'mobilegrid_11',
            'SET': [{
                'PATH': ['member'],
                'ID': 'mobilelabel_16',
                'ATTR': 'visible',
                'TRANSFORMATION': function(value, element) {
                    member = localStorage.getItem("member");

                    if (value == member) {
                        $(element).addClass("bubble-left");
                    } else {
                        $(element).addClass("bubble-right");
                    }

                    $.mobile.silentScroll(element.position().top);

                    //element.scrollTop(element[0].scrollHeight);

                }
            }, {
                'PATH': ['content'],
                'ID': 'mobilelabel_16',
                'ATTR': '@'
            }]
        }, {
            'PATH': ['ts'],
            'ID': '___local_storage___',
            'ATTR': 'ts'
        }],
        'requestMapping': [{
            'PATH': ['channel'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'channel'
        }, {
            'PATH': ['ts'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'ts'
        }]
    });

    datasources.push(messageDataSource);

    postMessageDataSource = new Apperyio.DataSource(postMessage, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("profile");
        },
        'onSuccess': function(data) {
            setText('profile_mobiletextinput_46', '');
            try {
                messageDataSource.execute({})
            } catch (ex) {
                console.log(ex.name + '  ' + ex.message);
                hideSpinner();
            };
        },
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['content'],
            'TYPE': 'STRING',
            'ID': 'mobiletextinput_46',
            'ATTR': 'value'
        }, {
            'PATH': ['member'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'member'
        }, {
            'PATH': ['type'],
            'TYPE': 'STRING',
            'ATTR': '1'
        }, {
            'PATH': ['direction'],
            'TYPE': 'STRING',
            'ATTR': '1'
        }, {
            'PATH': ['channel'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'channel'
        }, {
            'PATH': ['session'],
            'TYPE': 'STRING',
            'ATTR': '1'
        }]
    });

    datasources.push(postMessageDataSource);

    /*
     * Events and handlers
     */

    // Before Show
    var profile_beforeshow = function() {
            Apperyio.CurrentScreen = "profile";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var profile_onLoad = function() {
            profile_elementsExtraJS();

            localStorage.setItem("ts", 0);
            localStorage.setItem("messageData", null);
            localStorage.setItem("channel", 2);

            ;

            // TODO fire device events only if necessary (with JS logic)
            profile_deviceEvents();
            profile_windowEvents();
            profile_elementsEvents();
        };

    // screen window events
    var profile_windowEvents = function() {

            $('#profile').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });
            $('#profile').on({
                pageshow: function() {
                    try {
                        messageDataSource.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                },
                pagehide: function() {
                    var t = localStorage.getItem("timer");
                    clearInterval(t);
                    localStorage.setItem("timer", 0);
                },
            });

        };

    // device events
    var profile_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var profile_elementsExtraJS = function() {
            // screen (profile) extra code

        };

    // screen elements handler
    var profile_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#profile_mobilefooter [name="mobilebutton_29"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            postMessageDataSource.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#profile_mobilefooter [name="mobilebutton_29"]');

        };

    $(document).off("pagebeforeshow", "#profile").on("pagebeforeshow", "#profile", function(event, ui) {
        profile_beforeshow();
    });

    if (runBeforeShow) {
        profile_beforeshow();
    } else {
        profile_onLoad();
    }
};

$(document).off("pagecreate", "#profile").on("pagecreate", "#profile", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    profile_js();
});