/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '571c8f48-30e4-4f79-bcd1-002410b6b1dd';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "selectScreen",
    "location": "selectScreen.html"
}];

startScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'signingInLabel': 'startScreen_signingInLabel',
        'loginWithGoogleBtn': 'startScreen_loginWithGoogleBtn',
        'mobilelabel_15': 'startScreen_mobilelabel_15',
        'mobilegrid_9': 'startScreen_mobilegrid_9',
        'mobilegridcell_10': 'startScreen_mobilegridcell_10',
        'mobilebutton_14': 'startScreen_mobilebutton_14'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 536px;user-zoom: fixed;max-zoom: 1;min-zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;max-zoom:1;min-zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'startScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    membersDataSource = new Apperyio.DataSource(members, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['items'],
            'ID': 'mobilegrid_9',
            'SET': [{
                'PATH': ['id'],
                'ID': 'mobilebutton_14',
                'ATTR': 'visible',
                'TRANSFORMATION': function(value, element) {
                    $(element).data("member-id", value);
                }
            }, {
                'PATH': ['name'],
                'ID': 'mobilebutton_14',
                'ATTR': '@'
            }]
        }],
        'requestMapping': [{
            'PATH': ['channel'],
            'TYPE': 'STRING',
            'ATTR': '2'
        }]
    });

    datasources.push(membersDataSource);

    /*
     * Events and handlers
     */

    // Before Show
    var startScreen_beforeshow = function() {
            Apperyio.CurrentScreen = "startScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events
    var startScreen_windowEvents = function() {

            $('#startScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var startScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var startScreen_elementsExtraJS = function() {
            // screen (startScreen) extra code

        };

    // screen elements handler
    var startScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#startScreen_mobilecontainer1 [name="loginWithGoogleBtn"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        auth();

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="loginWithGoogleBtn"]');

            $(document).off("click", '#startScreen_mobilecontainer1 [name="mobilebutton_14"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var member = $(event.target).data("member-id");
                        localStorage.setItem("member", member);
                        Appery.navigateTo("selectScreen", {
                            transition: 'slide'
                        });

                    }
                },
            }, '#startScreen_mobilecontainer1 [name="mobilebutton_14"]');

        };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        startScreen_beforeshow();
    });

    if (runBeforeShow) {
        startScreen_beforeshow();
    } else {
        startScreen_onLoad();
    }
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});